name: release-docker

on:
  workflow_dispatch:
    # inputs:
    #   version:
    #     description: "release version/tag"
    #     required: true

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PWD }}

      - name: test docker
        run: |
          docker pull busybox
